// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qootuobjknnnjnldbzdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvb3R1b2Jqa25ubmpubGRiemRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTE0MzUsImV4cCI6MjA2NDQyNzQzNX0.8Sa1KhMown8B729rDVqlmwLEcU_xxFF4PdgqhpMmEUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);